S03-operators/range-basic.t

Change Range excludes_ methods to dashes

---

S32-io/io-path.t

Cf https://github.com/rakudo/rakudo/commit/00b44eb369b858b0cdd5cb3157090d2ea72a5799

Update  S32-io/io-path.t to use .IO instead of .path and test :basename, :dirname args

---

S03-metaops/hyper.t

With this, S03-metaops/hyper.t is clear on glr.

Add tests for binary op (non-)dwim cases and fudge broken ones

---

S32-str/encode.t

See MoarVM/MoarVM#289, perl6/nqp#251, and rakudo/rakudo#576.

Test non-encodable characters

---

S12-class/attributes-required.t

is required used as default checks

---

S06-operator-overloading/sub.t
S06-operator-overloading/term.t
S12-meta/exporthow.t

merge after: https://github.com/rakudo/rakudo/pull/603

tests EVAL with %*LANG modifications

---

S32-io/open.t

Not all possible mode combinations are tested, but at least now *some* are ;)
Next on the list: Write documentation.

add S32-io/open.t that tests extended open modes

---

S32-io/open.t

test default open mode, including failure to open nonexistent files

---

S32-temporal/DateTime.t

see https://github.com/rakudo/rakudo/pull/638 and RT 126948

Add test for subsecond ISO 8601 timestamp

---

S32-num/rat.t

See https://github.com/rakudo/rakudo/pull/706 for the corresponding rakudo PR to actually fix this.

Tests that Rat.perl to actually generates valid code

---

S07-hyperrace/hyper.t
S07-hyperrace/race.t

Notice that the `.race.map` is the only one that currently works.

Test hyper and race in reverse

---

S32-num/power.t

Upon the request in https://github.com/perl6/roast/pull/95#issuecomment-170444410 .

introduce X::Numeric::Overflow

---

S02-types/range.t
S07-iterators/range-iterator.t

(It will need some review before being put back in spectest.data)
Also, add a couple extra immutability tests on Range

Start to rehabilitate Range Iterator test file post-GLR

---

S04-statements/return.t

We can't test for 'Attempt to return outside of any Routine'
with our toolchain from Test.pm or Test::Util.

Use 'run' to test for returning outside of routine

---

S32-list/squish.t

Merge this when PR#685 is merged

Add tests for squish fixes in PR#685

---

S02-literals/adverbs.t

Add test for RT #128306

---

S16-filehandles/mode.t

Requires a Rakudo built with PR #773 (https://github.com/rakudo/rakudo/pull/773)

Test for RT #125489

---

S26-documentation/07-tables.t

incorporates a more complete test for problems found by Zoffix

add a more complex table test for a future bug fix

---

S06-signature/types.t

Requires a Rakudo built with https://github.com/rakudo/rakudo/pull/791

Test for RT #128392

---

S32-str/chop.t

Requires https://github.com/rakudo/rakudo/pull/814

Tests for RT #125814

---

S12-introspection/meta-class.t

[RT#128579](https://rt.perl.org/Ticket/Display.html?id=128579)
Can be merged after Rakudo PR merge: https://github.com/rakudo/rakudo/pull/818

Test basic metamethods for a Package

---

S16-io/eof.t

Reading /proc files line by line does not go into infinitive loop

---

S02-types/bool.t

depends on https://github.com/rakudo/rakudo/pull/836

tests for RT#127019

---

S02-types/native.t

Currently fudged for MoarVM due to a bug.

Add some tests for native-typed class elements.

---

S04-declarations/multiple.t

Implemented in Rakudo PR 854 (https://github.com/rakudo/rakudo/pull/854).

Tests for the fix for RT #118607

---

S02-literals/adverbs.t

Requires Rakudo PR #855 (https://github.com/rakudo/rakudo/pull/855).

Test for RT #117739

---

S03-operators/repeat.t

Tests for 'a' x NaN, Inf, * and variations.

Tests for RT #125628

---

S06-multi/syntax.t

Make sure where-blocked multi is prior to non-where-blocked multi

---

S16-io/eof.t

Currently, testing `S16-io/eof.t` assumes that `/proc/1/comm` is available.
In fact, it's only available since Linux 2.6.33. So this PR remove this assumption and get the first readable file under `/proc/1` to test.
Fix RT #128831

Picking first file from /proc/1 for eof testing

---

S32-list/duckmap.t

Test needed in order to close RT #129321.

Tests added for duckmap

---

S26-documentation/07-tables.t
S26-documentation/07a-tables-todo-skipped.t

Added tests for issue RT #129862. Also divided table tests into two groups for better tracking.

Bug 129862

---

S03-metaops/reduce.t

RT#128757: https://rt.perl.org/Public/Bug/Display.html?id=128757

Tests for non-numeric argument to reduce ([+] 'hello')

---

S32-basics/pairup.t

Proposed fix for [this issue](https://github.com/perl6/roast/issues/163)

Add tests for pairup.

---

S32-list/reduce.t

Trying to work on this for hacktoberfest.
* Closes #62

Add test for reduce with one item

---

S03-operators/bag.t
S03-operators/mix.t
S03-operators/set.t

These are the tests for PR https://github.com/rakudo/rakudo/pull/911

Test updated for proper bag/mix symmetric difference

---

S03-metaops/hyper.t
S32-list/duckmap.t

Rakudo implementation in rakudo/rakudo#915

RT #129363: duckmap preserves structure types

---

S17-procasync/basic.t

I wonder if this test good enough, feel free to edit or point out anything.
It checks stdout and stderr. It fails on rakudo before a fix and passes on latest.

A test for #130291

---

S15-unicode-information/uniprop.t

https://github.com/MoarVM/MoarVM/issues/448

Add tests for uniprops and add a fudged test for a MoarVM bug

---

S32-list/cross.t

Needed in order to close the RT.

Add test for RT #126508

---

S04-blocks-and-statements/temp.t

Attempt to resolve issue #199 
Not a frequent test contributor and am open to improvement suggestions.

Add tests for temp whole array / whole hash

---

S03-operators/precedence.t

Superscript exponent precedence tests

---

S32-io/socket-host-port-split.t

Tests for bug fix: https://rt.perl.org/Public/Bug/Display.html?id=130474

Added test for resolved bugfix RT #130474

---

S32-io/socket-fail-invalid-values.t

For RT issues:
https://rt.perl.org/Ticket/Display.html?id=130475
https://rt.perl.org/Ticket/Display.html?id=130473

Added test to fail on invalid port or family values

---

S12-meta/TestHOW.pm
S12-meta/classhow.t

Test for RT 125135 which was fixed by https://github.com/rakudo/rakudo/commit/0c0dd826e0

Test for RT 125135

---

S15-unicode-information/uniprop.t

Diacritic, Default_Ignorable_Code_Point, ID_Start,
IDS_Binary_Operator, IDS_Trinary_Operator

uniprop: add tests for 5 more properties

---

S05-metasyntax/longest-alternative.t

Test for RT #130562, ltm alternation only sees first sequential alternative.

Test for RT #130562

---

S03-operators/range.t

Please review carefully, as I'm not accustomed to adding stuff to roast.

Add tests for RT #130554

---

S32-io/IO-Socket-INET.t

Tests for fixes:
https://github.com/MoarVM/MoarVM/commit/8b195f641c
https://github.com/MoarVM/MoarVM/commit/17acfbe617
without them the test will SEGV

Test moarvm 234

---

S03-feeds/basic.t
S04-declarations/will.t
S32-array/exists-adverb.t
S32-hash/exists-adverb.t

As requested in comment on Issue #226.

Fix typo misspellings of fudge implementation niecza

---

README.md

Describe use of fudgeandrun to simplify fudge and run/prove individual test files.

Update README.md to mention fudgeandrun

---

S03-operators/ternary.t

Add tests for unicode version of ?? !!

Add tests for unicode version of ?? !!

---

S32-str/parse-names.t

Rakudo implementation (awaiting merge): https://github.com/rakudo/rakudo/pull/1031

Test Str.parse-names / &parse-names routine

---

S03-operators/misc.t

Rakudo PR: https://github.com/rakudo/rakudo/pull/1032

Tests for ≤ ≥ ≠ unicode ops

---

S11-modules/lib/Cool/Beans.pm6
S11-modules/lib/Cool/Cat.pm6
S11-modules/lib/Cool/Cat/Goes/Splat.pm6
S11-modules/require.t

Tests for latest require issues

---

S02-types/int-uint.t

Previously they checked that assigning a literal more than max or less
than min would (over|under)flow. However, the correct behavior is to
throw in those cases, but (over|under)flow if modifying the variable.
Some discussion with @jnthn about this here: https://irclog.perlgeek.de/perl6-dev/2017-03-12#i_14249599

Correct tests of (over|under)flow and assignment

---

S32-list/flat.t

Add some basic tests for `flat`.
Proposed fix for #230.

Add tests for `flat`.

---

S03-operators/bit.t

RT#126942: https://rt.perl.org/Ticket/Display.html?id=126942
RT#13278: https://rt.perl.org/Ticket/Display.html?id=131278

Test right bit shift for negative numbers

---

S02-types/sethash.t

See https://github.com/MoarVM/MoarVM/issues/603

Fudged three tests which upsets uthash

---

S29-os/system.t

Use `LEAVE { chdir $orig-cwd }` to fix being left in a different directory for remaining tests.
Use `$*EXECUTABLE.absolute` so the proper interpreter is always used.

Fix proc test failing due to prior chdir

---

S15-nfg/concat-stable.t

Remove shebang line from script

---

S06-operator-overloading/prefix.t

RT#124974 easiest. RT#124975 resolution. RT#124976 ever. RT#124977

Stop skipping tests that have been working since 2015.10

---

S19-command-line-options/03-dash-p.t

...which seems to have been resolved at some point.
Still fudged for JVM due to different bug.

Add test for RT#124247

---

S17-supply/watch-path.t

Add explicit checks around the events that occur for file system events. 
Test to cover RT #132043

Adding new tests around watching files

---

S02-types/native.t
S02-types/whatever.t
S03-metaops/hyper.t
S03-operators/precedence.t
S04-blocks-and-statements/temp.t
S06-operator-overloading/infix.t
S06-operator-overloading/workout.t
S06-signature/closure-parameters.t
S09-autovivification/autovivification.t
S09-typed-arrays/native-str.t
S12-coercion/coercion-types.t
S12-enums/basic.t
S12-introspection/WHAT.t
S32-num/stringify.t

Sorry for the noise but it makes it easier to revert if any of these cause issues.

Unskips and various roast cleanups

---

S02-types/whatever.t

RT#126540 RT#130773 RT#130502 RT#131846 RT#131409 RT#126984 tests

---

S11-modules/export.t
packages/RT129215.pm6

Perplexingly not be replicable by CompUnit::, needs a real "use"

Add fudged tests for RT#129215

---

S32-hash/perl.t

Add tests for RT#132119

---

S32-array/delete-adverb.t

:delete on lazy Arrays

---

S02-types/int-uint.t

Add tests for type byte

---

S28-named-variables/inittime.t

Add tests for $*INITTIME

---

S04-phasers/in-loop.t

So far phase POST has had problem when in-loop
I'm not sure if the plan number is right(for I fudge one test), besides, if I fudge the test in the right way.
It should be mention that POST not always see no outer $_
https://github.com/perl6/roast/blob/e10d7819126d10a2731ecf00f0dcfd5abf595b56/S04-phasers/pre-post.t#L81-L95

Test for RT #125488

---

S02-types/list.t
S02-types/range.t

@usev6 the merged test have comment `#?rakudo.jvm todo`, plz check.

Merge tests for same purpose

---

S26-documentation/07a-tables.t
S26-documentation/07c-tables.t

add new tests for fix to rakudo repo issue #1282

---

S26-documentation/07-tables.t

requires rakudo fix for RT #126740 (rakudo PR #1303)

adds test for fix for RT #126740, populates table caption property

---

S32-list/rotor.t

These two tests need something to the effect of https://github.com/rakudo/rakudo/pull/1454 to succeed.

Add tests for List.rotor with Whatever and Inf

---

S06-operator-overloading/prefix.t

Closes https://github.com/rakudo/rakudo/issues/1477
Closes https://github.com/rakudo/rakudo/issues/1315

Test post-inc/dec op optimization does not affect custom ops

---

S32-io/IO-Socket-INET.t

Skip on windows and WSL workaround for now to avoid hanging.  As mentioned in patch there is an RT and if we note workaround on ticket someone could come back and fix more fully later.

Skip repeated socket close test on windows rather than hang.

---

S02-names-vars/names.t

Do not merge before https://github.com/rakudo/rakudo/pull/1609.
See https://github.com/rakudo/rakudo/issues/1606

Implement Metamodel shortname tests

---

S24-testing/fails-like.t
packages/Test/Util.pm

To go with https://github.com/rakudo/rakudo/pull/1664

Spec fails-like and swap to core fails-like for tests that use it

---

S04-exceptions/fail.t

Checking that it fails and effectively includes the important message.

Adds test for RT#126394

---

integration/advent2011-day23.t
integration/advent2011-day24.t
packages/RT125245.pm

This will fix #420 when cherry picked onto 6.c-errata

replace use of README.md (which doesn't exist on 6.c-errata) by $?FILE

---

S26-documentation/07a-tables.t

Additional changes:
+ add tests for existing test tables that had no explicit tests

Add tests for fix for GH #1821: unexpected table failure

---

S32-array/splice.t

Closes https://github.com/rakudo/rakudo/issues/1843

Cover splice past end bugs

---

S06-currying/positional.t

Testing that .assuming a sub with slurpy param compiles without error.
See [Github Issue #1918](https://github.com/rakudo/rakudo/issues/1918)

Rakudo Issue 1918: Test Slurpy Positional params with .assuming

---

S26-documentation/04a-input-output.t

for code/input/output expected failures due to user pod errors

add new tests

---

APPENDICES/A02-some-day-maybe/io-cathandle.t
APPENDICES/README.md
S32-io/io-handle.t

POVI (Proof-Of-Viability Implementation): https://github.com/rakudo/rakudo/pull/2081

Spec for IO::[Cat]Handle.WRITE/.READ/.EOF methods

---

S03-operators/arith.t
S32-num/fatrat.t
S32-num/rat.t

POV: https://github.com/rakudo/rakudo/pull/2314

Normalize ZDRs

---

S02-magicals/KERNEL.t

Also see: https://github.com/perl6/doc/issues/2395

Add basic hostname test

---

S12-enums/misc.t

Per https://github.com/rakudo/rakudo/issues/2073

Spec Enum:D does NOT accept Enum:U

---

S32-io/IO-Socket-Async.t

This tests for regressions of:
https://github.com/rakudo/rakudo/issues/2411

Tests listening on port 0 returns usable tap with whenever

---

S12-methods/qualified.t

These tests are covering fixes to rakudo compiler provided with pull request #2675.

More tests for qualified method calls

---

S14-roles/typecheck.t
packages/Roles/lib/GH2613.pm6

Test case for fixed https://github.com/rakudo/rakudo/issues/2613

Test for #2613

---

S06-multi/compile-time.t
packages/S06-multi/lib/compile-time.pm6

Support for rakudo/rakudo#2780, rakudo/rakudo#2772

Test for GH #2772

---

S03-operators/misc.t

PR: rakudo/rakudo#2790
Ticket: rakudo/rakudo#2786

Changes to conform with fix of use of Real type object in operators

---

APPENDICES/A03-older-specs/01-misc.t
MISC/bug-coverage-6.d.t
MISC/misc-6.d.t
S04-declarations/constant-6.d.t
integration/advent2010-day03.t

In support of PR rakudo/rakudo#2852

Removed all .REVIEW modificators from v6.d

---

S04-phasers/enter-leave.t

In a previous version of rakudo, when a block had no local variables,
the ENTER phaser would not successfully decont a variable from a
surrounding scope. This didn't have a ticket and was apparently fixed
in rakudo as a side-effect of 541a4f1628.
This is maybe not the most golfed-down test but I couldn't find a way to
avoid the loop and hence the other things that help me avoid having
local variables in the block.
Cf. https://colabti.org/irclogger/irclogger_log/perl6?date=2019-04-26#l196 and onwards.

Add test for decont in ENTER phaser

---

S17-scheduler/at.t
S17-scheduler/every.t
S17-scheduler/in.t

Related to https://github.com/rakudo/rakudo/pull/2819

Unit test ThreadPoolScheduler.cue edge cases with :at/:in/:every

---

S17-scheduler/at.t
S17-scheduler/every.t
S17-scheduler/in.t

Revert "Unit test ThreadPoolScheduler.cue edge cases with :at/:in/:every"

---

S32-list/head.t

Adds tests for https://github.com/rakudo/rakudo/issues/2862

Add tests for #2862

---

S05-metasyntax/regex.t

A test for https://github.com/rakudo/rakudo/issues/2901
Needs
https://github.com/perl6/nqp/pull/540
https://github.com/rakudo/rakudo/pull/2907
to be merged to pass.

Add test for GH #2901

---

S12-meta/classhow.t

Closes https://github.com/rakudo/rakudo/issues/2602

Add test for GH #2602

---

S03-metaops/hyper.t

Tries to address https://github.com/rakudo/rakudo/issues/2480
I am not sure if this is all that is needed, can someone suggest something better?

Add test for GH # 2480

---

VERSION
integration/advent2010-day03.t
spectest.data

In support of rakudo/rakudo#2852

Add revision 6.e

---

S10-packages/precompilation.t

Test for https://github.com/rakudo/rakudo/issues/1219

Test for https://github.com/rakudo/rakudo/issues/1219

---

VERSION
docs/announce/6.e.md
docs/release-guide.md

This version is most like incomplete and most definitely contains
errors. Review is required.

Changed release guide to reflect the latest state of things.

---

S11-modules/export.t

rakudo/rakudo#2955
rakudo/rakudo#2964

Test for exported role

---

S11-modules/gh2979.t
packages/S11-modules/lib/GH2979-Foo.pm6
packages/S11-modules/lib/GH2979.pm6

Add tests for non-containerized exports

---

S03-operators/assign.t

Support for rakudo/rakudo#3013

Test for SetHash assignment

---

S02-names/SETTING-6c.t
S02-names/SETTING-6d.t
S02-names/pseudo.t
S04-declarations/constant.t
S04-declarations/my.t
S29-context/die.t
packages/Test-Helpers/lib/Test/Util.pm6

Support for fixed pseudo-packages

---

docs/announce/6.e.md

Document 6.e-related changes

---

S02-literals/string-interpolation.t

https://github.com/rakudo/rakudo/issues/3070

Test block interpolation in routine with signature-declared return value

---

S02-names/pseudo-6e.t
packages/S02-names/lib/GH3104_6d.pm6

Test for cross-language revision usage.
rakudo/rakudo#3104

Add tests for CLIENT:: pseudo-package

---

S02-names/pseudo-6e.t

Reverting a left-over of debugging process.

Fix for incorrect number of tests

---

S17-promise/illegal-transition.t
S17-promise/single-assignment.t
spectest.data

Added spectest requested in rakudo/rakudo/pull/3139

Spectest for rakudo/rakudo/issues/3137

---

S03-junctions/misc.t
S03-metaops/misc.t

Add test for freezing Junction

---

S03-junctions/misc.t
S03-metaops/misc.t
S32-hash/map.t

rakudo/rakudo#3168
perl6/problem-solving#99

Add tests for decontainerization of Hash -> Map coercion

---

S02-types/lazy-lists.t

Add tests for lazy iterators

---

S32-trig/sinh.t

Add test that sinh is 'odd'

---

S16-io/watch.t
spectest.data

Followup to rakudo/rakudo#3100

Add test for file change events.

---

S12-class/inheritance.t

Spec test for https://github.com/rakudo/rakudo/issues/2829 as suggested by @jnthn.
Closes https://github.com/rakudo/rakudo/issues/2829

Test Parameter subclassing

---

S02-types/pair.t

Just code provided by the ticket, closes
https://github.com/rakudo/rakudo/issues/1500

Test fake-infix adverbs on a construct

---

S32-io/signals.t
spectest.data

Add tests for R#3035

---

S29-context/eval.t

Support for rakudo/rakudo#3265,
Related to rakudo/rakudo#3263

Add test for EVAL preserving caller's compiler version

---

S32-list/seq.t

Closes https://github.com/rakudo/rakudo/issues/2976

Test caching by elems call on Seq

---

S03-metaops/hyper.t

Closes https://github.com/rakudo/rakudo/issues/2482

Test hyperop results in a slip

---

S32-str/samemark.t

Revert "Add samemark tests for prepend and flags"

---

S10-packages/precompilation.t
packages/S10-packages/lib/GH2897-A.pm6
packages/S10-packages/lib/GH2897-B.pm6

In support of MoarVM/MoarVM#1209
Related to rakudo/rakudo#2897 and a number of other tickets.

Test for precompiled closures

---

S32-str/numeric.t

Via https://github.com/rakudo/rakudo/pull/3291

Add test to check UInt on non-numeric Str returns a Failure

---

S12-methods/syntax.t

Add test for `$.method: <args>` syntax

---

S14-roles/submethods-6e.t
S14-roles/submethods.t
spectest.data

This aspect wasn't covered previously. Yes, my bad, I overlooked it...

Test for basic behaviors of submethods in roles for 6.e

---

S12-construction/destruction.t
S12-construction/roles-6e.t

1. Unfudge _S12-construction/destruction.t_, remove deprecated use of `undefined`.
2. Fix the order of destructor invocation in _S12-construction/roles-6e.t_
Also, both tests are now using timeout-based detection of the first destructor invocation.
In support of rakudo/rakudo#3375

Adjust tests to correspond with fixed DESTROY order (fixed)

---

S14-roles/attributes.t

In support of rakudo/rakudo#3382 and rakudo/rakudo#3397

Add tests for class stuff prioritzing over role's

---

S12-methods/qualified.t

Also made test classes lexicals of their respective subtest block.
Related PR: rakudo/rakudo#3415

Test relaxed FQN method calls on a role from parent

---

S03-operators/eqv.t

This includes regression tests for rakudo/rakudo/pull/3446

Cover eqv between Seqs

---

S24-testing/fails-like.t

Support for https://github.com/rakudo/rakudo/pull/3464

Add tests for fails-like with Bool:D matcher

---

S12-class/rw.t
S14-roles/rw.t
spectest.data

In support of rakudo/rakudo#3496 and following rakudo/rakudo#3495

Add tests for `is rw` trait on roles

---

S03-operators/eqv.t

Add a regression test for rakudo/rakudo/issues/3346

Add regression test for rakudo/issues/3346

---

S32-io/pipe.t

Support for https://github.com/rakudo/rakudo/pull/3514

Add test for run with :out(Handle:D) and :merge

---

S06-advanced/dispatching.t

It must not break the dispatcher chain.

Added regression test for nextcallee

---

S06-advanced/dispatching.t

This test is ok when dispatcher implementation utilizing
`nextdispatcherfor/takenextdispatcher` ops is merged.

Add a regression test

---

S06-advanced/dispatching.t

Solves a problem described by @jnthn in Raku/problem-solving#170. When
the first multi-candidate of a method is wrapped on a parent class the
control is then returned to the `MethodDispatcher` causing the rest
multi-candidates to be skipped.

Cover special case of wrapping first multi-candidate

---

S04-statements/label.t

... as reported in https://github.com/rakudo/rakudo/issues/3622.

Test usage of labels within nested loops

---

S32-str/encode.t

```
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/6.c-errata.
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.
To https://github.com/Raku/roast
! [remote rejected]     6.c-errata -> 6.c-errata (protected branch hook declined)
error: failed to push some refs to 'https://github.com/Raku/roast'
```
is not very handy. Apparently, I am not authorized enough to do what release manager does anymore.

Cherry-pick a commit

---

S02-types/subset-6e.t

See https://github.com/rakudo/rakudo/pull/3589

Update tests WRT X::Syntax::Variable::MissingInitializer's new msgs

---

S09-multidim/methods.t

This updates tests to match https://github.com/rakudo/rakudo/pull/3685

Update .gist tests for multidim arrays

---

S16-io/comb.t
S17-supply/comb.t
S32-str/comb.t

Tests for https://github.com/rakudo/rakudo/pull/3668

Test "aaaa".comb("aa") gives non-overlapping results

---

integration/advent2010-day03.t

And this one really closes #640
It's simply a matter of changing the files and its contents to an equivalent in this directory.

Fixes integration test

---

S32-exceptions/misc.t

Support for rakudo/rakudo#3752

Add test for a vcs conflict marker detection

---

integration/gather-with-loops.t
spectest.data

All of these tests are dying with an UnwindException on the
JVM backend currently, but they are passing on MoarVM.

Add more tests for gather/take

---

spectest.data

This re-alphabetizes the file listing.

alphabetize test file names

---

docs/announce/6.d.md
rosettacode/sierpinski_triangle.t

Update a public facing perl6.org url in the 6.d announcement

Lathropd patch 3

---

S05-modifier/ignorecase.t
S05-modifier/ignoremark.t

Related to rakudo/rakudo#3815.

Test for empty string match with ignore-case and ignore-mark

---

TODO
docs/announce/6.e.md
rosettacode/sierpinski_triangle.t

Update some public-facing perl6 references

Lathropd patch 2

---

S24-testing/15-done-testing.t
spectest.data

Test Test::done-testing( --> Bool)

Fix #669 by using is_run

---

S12-subset/subtypes.t

Test `&`-sigiled variables in `where` clauses

---

S32-str/encode.t

Closes  https://github.com/Raku/roast/issues/526

Fix test to use Buf, as advertized, not Blob

---

fudgeandrun

Most likely needs overhaul to handle p6->raku rename changes that occured

Make script find local rakudo binary

---

S12-subset/subtypes.t

Addresses comments on https://github.com/Raku/roast/pull/677
* Fix erroneous test https://github.com/Raku/roast/pull/677#discussion_r498638109
* Add multi dispatch tests
* Add tests with Block and Whatever values in variable

Improve where &-sigiled tests

---

S03-operators/set_addition.t
S03-operators/set_difference.t
S03-operators/set_intersection.t
S03-operators/set_multiply.t
S03-operators/set_symmetric_difference.t
S03-operators/set_union.t

To be merged after https://github.com/rakudo/rakudo/pull/3950 has
been merged.

Add tests for R#3945

---

S32-exceptions/misc.t

To be merged after https://github.com/rakudo/rakudo/pull/3951 has
been merged

Add tests for R#3949

---

S03-operators/set_addition.t
S03-operators/set_difference.t
S03-operators/set_elem.t
S03-operators/set_equality.t
S03-operators/set_intersection.t
S03-operators/set_multiply.t
S03-operators/set_precedes.t
S03-operators/set_proper_subset.t
S03-operators/set_subset.t
S03-operators/set_symmetric_difference.t
S03-operators/set_union.t

These were seen to be uncovered by a coverage report.

Add tests for set op multis that take Failures

---

S02-types/set.t

Test two uncovered methods in Set.pm6

---

S32-temporal/DateTime-Instant-Duration.t

Also test a Duration defaults to 0.0 if not given a value.

Mostly Duration % Real tests

---

S12-methods/multi.t

In support for rakudo/rakudo#3977.

Add and fix tests for multi-dispatching methods

---

S32-io/io-path-symlink.t

Tests for https://github.com/rakudo/rakudo/pull/3980

Add tests for relative symlinks

---

S02-types/bag.t
S02-types/mixhash.t

Fix incorrect use of `isa-ok`

---

APPENDICES/A02-some-day-maybe/misc.t
S05-match/basics.t
S06-currying/positional.t
S12-coercion/coercion-methods.t
S12-coercion/coercion-types.t
S12-coercion/parameterized.t
integration/weird-errors.t
spectest.data

In support of rakudo/rakudo#3891

Tests for the new coercion semantics

---

S02-types/flattening.t

Regression test for rakudo/rakudo/issues/4034.

Cover push/unshift with multiple values

---

S12-coercion/coercion-types.t

`1` and `e` are incorrect values for Rat(Str). Replaced with `1.0` and
`<2.71>`. The latter as an additional measure to make sure allomorphs
are treated correctly.
Also added tests for errors when invalid coerctions are attempted.

Fix incorrect coercion spectest

---

S12-coercion/coercion-types.t

`my Str(Int(Cool)) $x = 42.31;` results in string "42".

Add a test for nested coercions

---

S02-types/nominalizables.t

In support of rakudo/rakudo#4073

Add tests for coercive subsets

---

S02-types/nominalizables.t

In support of rakudo/rakudo#4082.
Not currently adding a test for declaring an uninitialized variable
of type  `OfDef` because prior to 6.e a subset was matching itself,
event if refinee is a definite.

Add tests for subsets of definites

---

S03-metaops/reverse.t

In support for [#4204](https://github.com/rakudo/rakudo/pull/4204)

Add test for R-metaop as value in colon pair

---

S06-other/main-usage.t

Add tests for whitespace-delimited CLI arguments

---

S32-temporal/juliandate.t
spectest.data

This PR adds a new test file for Rakudo PR #4288.

Add tests for new methods on class DateTime with PR #4288

---

S32-temporal/baum-gregorian-data.t
spectest.data

Extends tests of class DateTime to negative Gregorian dates

Add Gregorian test data including negative dates

---

S02-literals/allomorphic.t

Add tests for substr-rw on allomorph types

---

S14-roles/parameterized-basic.t

Test for cases:
role R[::T] is T {}
role R[::T] does T {}
In support of rakudo/rakudo#4407

Add tests for indirect inheritance and role consuming

---

S32-io/mkdir_rmdir.t

The added tests should pass for MoarVM/MoarVM#1507.  Edit: the final diff is confusing, please consider viewing each commit for the actual changes.

Test cases where mkdir should fail

---

S32-io/mkdir_rmdir.t

The required MoarVM PR has been merged and the todo is passing now.

Unfudge test

---

S05-metasyntax/regex.t

Closes https://github.com/rakudo/rakudo/issues/2118

Add tests for #2118

---

S06-signature/unspecified.t

Closes https://github.com/rakudo/rakudo/issues/1358

Add test for #1358

---

S32-list/create.t

Closes https://github.com/rakudo/rakudo/issues/2060

Add test for #2060

---

S03-sequence/misc.t

Closes https://github.com/rakudo/rakudo/issues/2920

Add test for #2920

---

S03-metaops/misc.t

Closes https://github.com/rakudo/rakudo/issues/1890

Add test for #1890

---

S03-smartmatch/signature-signature.t

Requires https://github.com/rakudo/rakudo/pull/4479.

Uncomment a test in S03-smartmatch/signature-signature.t

---

S12-construction/destruction.t

Sometimes under heavy load we'd hit the timeout instead of a GC
triggering the destructor. So instead, just loop until we hit it, but
add in a call to explicitly request a GC (which wasn't available when
this test was written).

Simplify the code used to test destructors

---

S32-num/is-prime.t

Add some cases that test the MoarVM bug fixed by
https://github.com/MoarVM/MoarVM/pull/1587.

Some more tests that negative numbers aren't prime

---

S12-class/mro-6e.t

In support of rakudo/rakudo#4635

Add tests for :concretizations parameter of .mro

---

S03-operators/range.t

Make sure `Range` `ACCEPTS` does the right thing when operates on numeric ranges.
In support of rakudo/rakudo#4687

Add tests for coercing LHS in smartmatch against ranges when needed

---

S03-junctions/autothreading.t
S03-smartmatch/00-sanity.t
S04-statements/given.t
spectest.data

In support of rakudo/rakudo#4653

More tests for smartmatch and given/when

---

S03-smartmatch/array-hash.t
S03-smartmatch/array-map.t
spectest.data

In support of rakudo/rakudo#4688

Add smartmatch tests for Map

---

S03-junctions/autothreading.t
S03-junctions/misc.t
S03-smartmatch/any-pair.t
S04-statements/given.t
S14-roles/typecheck.t

In support of rakudo/rakudo#4698

Adjust some smartmatch and given/when tests

---

S03-junctions/misc.t

Make sure `say`, `put`, `print`, and `note` all work as expected.

Add tests for basic IO over junctions

---

S02-types/int-uint.t
S09-typed-arrays/native-int.t

This shouldn't change any functionality (except for fudging some tests
for the JVM backend).

Tweak some uint tests

---

S06-advanced/dispatching.t

Skip only those not actually working yet.
Related to rakudo/rakudo#4761

Unfudge some working tests

---

S06-advanced/dispatching.t

Revert "Unfudge some working tests"

---

S03-junctions/misc.t

Related to Raku/problem-solving#311 and PR rakudo/rakudo#4769

Ensure junctions are value objects

---

S04-statements/given.t

In support of rakudo/rakudo#4860 to cover rakudo/rakudo#4850

Add test for topic within a nested closure

---

S04-declarations/will-complain.t
spectest.data

Add tests for `will complain`

---

S06-signature/passing-arrays.t

I have found none. Therefore this test is covering rakudo/rakudo#4864 and also covers other cases.

Add tests for positional bind failover

---

S17-lowlevel/lock.t

Add tests for Lock::Soft

---

S06-signature/passing-arrays.t

To be merged if https://github.com/rakudo/rakudo/pull/4947 is merged

Mark test as todo

---

S12-attributes/delegation.t

Ensure that `handles(*)` works on a child class when the delegating attribute is declared on parent.
In support of rakudo/rakudo#4966

Add test for delegation with children classes

---

S06-advanced/return.t
S12-coercion/coercion-return.t
S12-coercion/coercion-types.t
spectest.data

It was previously failing due to a wrong syntax.

Unfudge an actually working test

---

S12-coercion/coercion-methods.t

In support of rakudo/rakudo#4982.

Test for coercion regression on roles.

---

S04-declarations/my-6c.t

Related to rakudo/rakudo#3919 and rakudo/rakudo#5027

Add more tests for sigilless declarations

---

S14-roles/parameterized-type.t

In support of rakudo/rakudo#5044

Add a test for role parameterization of generics

---

S12-coercion/coercion-types.t

Cover edge cases fixed with rakudo/rakudo#5046

Add tests for coercive parameters

---

S06-signature/type-capture.t

In support of https://github.com/rakudo/rakudo/pull/5048

Add tests for type captures used in signature return

---

S09-hashes/objecthash.t

Enforces https://github.com/rakudo/rakudo/issues/5165 should not happen.

Test for parameterised hashes as entries to store

---

S14-roles/stubs.t

... as multi method in class. Compare
https://github.com/Raku/old-issue-tracker/issues/2901

Test implementing non-multi method stubbed in role

---

S17-promise/then.t

In support of rakudo/rakudo#5314

Add tests for Promise new `andthen` and `orelse` methods

---

test_summary

This is similar to what was done in
https://github.com/rakudo/rakudo/commit/fa9cd8ef55.

Teach test_summary about #rakuast fudging

---

S03-metaops/hyper.t

https://github.com/Raku/old-issue-tracker/issues/4700

Add test for issue 4700 in old issue tracker

---

S12-coercion/coercion-types.t

https://github.com/Raku/old-issue-tracker/issues/6176

Add test for issue 6176 in old issue tracker

---

S02-names/is_default.t
S02-types/is-type.t

In support of rakudo/rakudo#5477

Add tests for complex generic instantiation cases

---

S02-types/generics.t
spectest.data

In support of rakudo/rakudo#5493

Add test for instantiation of a generic class

---

6.c/S02-names/pseudo-6c.t
S02-names/pseudo-6e.t

In support of Raku/problem-solving#294 and rakudo/rakudo#4495

Additional tests for PseudoStash

---

S02-types/mu.t

Depends on https://github.com/rakudo/rakudo/pull/3978.
Fixes https://github.com/rakudo/rakudo/issues/1940

Add tests for Mu smartmatching

---

S32-num/complex-logarithms.t
S32-num/cool-num.t
S32-num/log.t

@librasteve presented new tests that are best presented in a new test file. The file includes links to good Wikipedia articles that reference pertinent subjects.
This PR should close issue #862.

Add log2 test file

---

S32-io/IO-Socket-INET.t

Depends on https://github.com/rakudo/rakudo/pull/5604

Test mixed bin/no bin access in IO::Socket
