S02-types/sethash.t
S03-operators/bag.t
S03-operators/mix.t
S03-operators/set.t

Up until now the behavior of mixes has been broken for the QuantHash ops.
This PR also sanitizes the expectation that `Set (-) Bag` returns a `Set`. Please make any arguments for why this should  be the case below, but please recognize that it essentially makes LoL processing for `(-)` more difficult, and overall reduces the DWIM-ness of the set operators.

Add a mix.t test

---

S32-array/delete.t

This test fails on rakudo nom, nqp master, MoarVM master for the reasons I reported in RT #125457. Contributing this test to detect the error now and any future regressions.

Adding a test for RT #125457 regressions

---

S15-nfg/cgj.t

Tests for how the COMBINING GRAPHEME JOINER is handled under NFG.
Necessary because it is a special case of a combining character with ccc=0.
More extensive tests would include making sure that other combining characters don't move from one side of CGJ to the other, including "merging" with the base character through the selection of a precomposed canonically equivalent form under NFC.

Create tests for the COMBINING GRAPHEME JOINER special case

---

S03-metaops/hyper.t

Fixed by https://github.com/rakudo/rakudo/commit/441d54d42e.

Defudge hyper tests that incorrectly die no more

---

S05-metasyntax/repeat.t

A recent change in NQP https://github.com/perl6/nqp/pull/249 added support for non inclusive range syntax as quantifiers in a regex. This adds spec tests to test that functionality

Add spectests for 1^..^10 non inclusive range quantifiers in regexs

---

S16-io/newline.t

Tested on both ubuntu linux and Windows 7

expand S16-io/newline.t tests to include Buf decoding

---

S06-operator-overloading/sub.t
S06-operator-overloading/term.t
S12-meta/exporthow.t

This fixes a race condition where 
```perl6
$lock.protect({ $cv1.signal; $cv2.wait });
```
would run before
```perl6
$lock.protect({ $cv1.wait });
```
which causes the test to hang forever. It only happened when I had TEST_JOBS set to >= to my cores. Not sure if this is a symptom of a greater bug or just something the test writer didn't consider.

fix S17-supply/syntax.t race condition

---

S32-io/io-spec-win.t

I filed a confused [bug report][1] thinking these tests were not passing because of a failure of IO::Spec to delegate to IO::Spec::Win32. Later, I realized that invoking methods on IO::Spec is wrong, and one must use $*SPEC. This chunk of the the test file probably did not get exercised much.
[1]: https://rt.perl.org/Public/Bug/Display.html?id=126876

Fix Win32 specific IO::Spec tests so they pass

---

S12-meta/MultiDeclare.pm
S12-meta/exporthow.t

tests for multiple things in `DECLARE` working in `EXPORTHOW`
don't merge yet. Rakudo patch incoming.

multiple declarators inside DECLARE

---

S32-list/permutations.t

These are edge cases that regularly get overlooked
In fact this is a response to finding out that it has once again stopped working.
Do not accept until [Rakudo pull request #686](https://github.com/rakudo/rakudo/pull/686) or similar fix has been accepted.
The number of permutations of an empty list is known in math to be 1

Test permutations(1) and (1,).permutations

---

S02-types/version-stress.t

This test uses the same values as S02-types/version.t, but tests all comparison
operators in all possible combinations, which produces 2035 tests instead of 36.

Add a stress test for Version

---

S32-list/seq.t

Fix #114
I have added tests for the from-loop method according to the following page
https://doc.perl6.org/routine/from-loop#class_Seq
But I don't have very much confidence. Can anyone review this tests ?
The following is the results of the from-loop tests
```
not ok 29 - from-loop(&body) returns a Seq
ok 30 - the Seq object is lazy
not ok 31 - from-loop(&body, &condition) returns a Seq
ok 32 - from-loop(&body, &condition) terminates calling &body if &condition returns False
not ok 33 - from-loop(&body, &condition, &afterward) returns a Seq
ok 34 - &afterward is called after each call to &body.
ok 35 - from-loop(&body, &condition, &afterward) terminates calling &body if &condition returns False
```

Add from-loop tests

---

S06-advanced/wrap.t

This PR doesn't change the spectest functionally, it's just rewrites the way one test is done.
The use of `throws-like` makes the pass/fail of the test depend on the specifics of implementation of `throws-like`. Depending on whether subtest` that `throws-like` use is a multi, different exception type will be thrown.
See https://github.com/rakudo/rakudo/pull/743 for [more detailed explanation](https://github.com/rakudo/rakudo/pull/743#issuecomment-210489723).

Rewrite test to avoid throws-like()

---

S26-documentation/07-tables.t

It's not uncommon to configure editors to auto-strip trailing whitespace
and this feature silently breaks tests in this file.

Add a warning for trailing-whitespace tests

---

S32-hash/exists-adverb.t

depends on https://github.com/rakudo/rakudo/pull/835

add test for :exists on multi-dim assoc subscript literals

---

S02-types/native.t

Also, silence a deprecation warning by using is-approx instead of
is_approx.
Once this is closed the [ticket](https://rt.perl.org/Public/Bug/Display.html?id=127813) can also be closed.

Unfudge some passing tests.

---

S03-operators/relational.t

100 ≅ -100 and 100 =~= -100 must return False
Fixed in Rakudo PR https://github.com/rakudo/rakudo/pull/787

Test RT#128421

---

S05-match/capturing-contexts.t

Test that non-ascii tokens work in regexes/grammars.
Requires a Rakudo built after https://github.com/rakudo/rakudo/commit/20ed9e2e2cdf47e5ea4ee46eac287287233620db

Tests for RT #127075

---

S29-os/system.t

Changes
===========
Add tests for `.command` and `.signal` methods for proc.
Proposed fix for https://github.com/perl6/roast/issues/166

Tests for Proc.command and Proc.signal

---

S32-list/duckmap.t

Assuming I have read between the lines of http://irclog.perlgeek.de/perl6/2016-09-26#i_13285724 correctly, these should verify `duckmap` behaviour slightly more. Comments?

A couple more duckmap tests

---

S32-num/power.t

The test for RT #112788 didn't work properly on 32-bit systems. This
has been fixed by changing the exponent from 9 to 8 so now it should
behave the same, i.e. hang, on both 32 and 64 bit systems. An
additional test was added (viki++) which checks that a Rat raised to
a very large number actually throws.

Fix test which breaks on 32 bit systems

---

integration/error-reporting.t

After the recent changes to backtrace handling this test
started to fail on rakudo-j. There are references to lines
in gen/jvm/CORE.setting which are causing the test to fail
because of the 's' in 'setting'.
Allowing additional lines in the backtrace still fits the test
description 'Thrown Failure outputs dual backtraces'.

Make test for output of backtrace less specific

---

integration/error-reporting.t

https://rt.perl.org/Public/Bug/Display.html?id=125247#ticket-history
The original ticket is about a proper error message for an unfinished multi-line comment. The error message should contain right line number, i.e. where the comment started.

Test for #125247

---

integration/error-reporting.t

Related to https://github.com/rakudo/rakudo/pull/957. Closes https://rt.perl.org/Public/Bug/Display.html?id=130211.
I just wrote checking of reverse-ordered role names to be independent from exact message.

A test for #130211

---

S12-methods/accessors.t

Fix some typos in test descriptions.

fix test description typos in S12-methods/accessors.t

---

S03-operators/bag.t
S03-operators/mix.t

This time, we don't change any of the set tests.
All of the 'showkv' calls were removed as they are no longer necessary
and several new tests to ensure symmetric behavior on (+) and (.) operators.

Re-introduce the fixes for bag/mix symdif

---

S19-command-line/arguments.t

Testcase for the bug mentioned in MoarVM/MoarVM#482.
I couldn't get the bug to reproduce with the is_run sub the rest of this file uses, so I borrowed the `is run($*EXECUTABLE, '-e'` pattern from another test file.

Add command line test for UTF-8 decoding of @*ARGS

---

S03-operators/repeat.t

Large repetition values for Str.x should not complain about negative
numbers or give an empty string as the result.
Requires Rakudo PR #867 (https://github.com/rakudo/rakudo/pull/867).

Tests for RT #128035

---

S26-documentation/08-formattingcodes.t

1. rejigs the array indexes so that the tests work without "" being everywhere ( and stops testing specifically for '")
2. adds a new test `B< < B<foo> > >` which used to fail
(don't merge yet)

Pod fc fixes

---

S26-documentation/block-trailing.t
S26-documentation/why-trailing.t

Hi All,
The attached tests are failing for me with the most recent rakudo.
My reading of S26 would be that it should be valid to have declarator pod trailing an attribute even if there is also an initialization of the attribute. 
thanks
Brian

Pod on declarator with initialization

---

fudgeall
fudgeandrun
t/01-implname.in
t/01-implname.out_impl-1.backend
t/01-implname.out_impl-2
t/02-version.in
t/02-version.out_v6.0.0
t/02-version.out_v6.0.3
t/02-version.out_v6.1.0
t/03-count.in
t/03-count.out_v6.0.0
t/04-combinations.in
t/04-combinations.out_impl.1
t/04-combinations.out_impl.2
t/05-skip.in
t/05-skip.out_impl-1
t/06-todo.in
t/06-todo.out_impl-1
t/07-register_function.in
t/07-register_function.out_impl-1
t/fudge.t
t/fudgeandrun.t

Continuation of work on issue #226.  Creates an implementation independent fudgeandrun that uses $*PERL.compiler.name and $*VM.name to come up with a default implementation but also takes an --impl parameter for something else. Since fudge was written based on a concept of an implementation and rakudo is the only active implementation, adding a --compiler in addition to --impl did not seem to make sense. --backend was left in for backward compatibility and --version was added for improved compatibility with fudge.
Patch includes an implementation independent test driver, t/fudgeandrun.t, that uses existing t/0[1-9]-*.in test files with a modification to test for implementation backends.  The existing fudge test input files are all updated so that their fudged output is runnable with …

Fudgeandrun move to roast

---

S10-packages/basic.t

This adds a test to ensure that 'for $x()' doesn't die with an error about this being Perl 5 code.
Rt ticket: https://rt.perl.org/Public/Bug/Display.html?id=131076#ticket-history
Commit that fixes this: rakudo/rakudo@87fe800d1d

Test fix for not dying on 'for $x()'

---

S32-exceptions/misc.t

Aligns the tests with https://github.com/rakudo/rakudo/pull/1073

Adapt tests to use new typed exception

---

S12-subset/subtypes.t

Wrote a test for RT 131381 that currently fails.
https://rt.perl.org/Public/Bug/Display.html?id=131381

Added test for RT 131381

---

S04-declarations/constant.t
packages/ExportConstant.pm6

Tests bug fixes introduced with this patch:
https://github.com/rakudo/rakudo/commit/dc4ed746ddeb562688985a41e9a51380d7bc0cf6
see RT #127858, #131705

Tests for constants with lexical scopes on the RHS

---

S09-subscript/slice.t

Lizmat++ for the actual bugfix. Closes https://rt.perl.org/Public/Bug/Display.html?id=131827

Test for #131827

---

S02-literals/heredocs.t

10 of these 11 new tests show tabs getting replaced with spaces when they shouldn't be.

additional failing heredoc tests

---

S12-methods/multi.t

The results of this test are correct for a runtime
mixin where roles were added one at a time... which
is one of the reasons why "does (Role1, Role2, Role3)"
exists.  So use it.  What probably happened in #124848
was the wrong fix was applied to the test after
"does" lost the associativity it was not supposed to have.

Fix incorrect/skipped test for RT#124848 (RT#69192)

---

S32-str/sprintf-b.t

Allows us to change some skips to todos
New RT#132040 added to deal separately with the "%+ " issue
Alters tests... will need cherry-pick into 6.c-errata as well

Alter tests to avoid unintended/irrelevant interpolation

---

S05-mass/rx.t

Added tests to cover the predefined subrule <ww>.  As explained
in RT #293, word boundary, <wb> is well tested but not <ww> which
has a seperate implementation in nqp.
These tests fill that void.
Resolves: RT #293

Added tests to cover <ww> - within word

---

S05-metasyntax/longest-alternative.t
S05-metasyntax/sequential-alternation.t

They're the bottom eight tests I listed in the description of the already merged NQP PR https://github.com/perl6/nqp/pull/368.
(The other ones listed there, for quantifiers, seem to be already covered in `S05-mass/rx.t`.)
This closes [RT #130117](https://rt.perl.org/Ticket/Display.html?id=130117) and  [RT #131973](https://rt.perl.org/Ticket/Display.html?id=131973).

Add tests for backtracking into alternations

---

S32-io/file-tests.t

This PR intends to expand the tests in `S32-io/file-tests.t`, as referenced in #118.

Expand file tests

---

S03-operators/arith.t

#132083: [REGRESSION] Broken math (-2147483648 != -2147483648)
https://rt.perl.org/Ticket/Display.html?id=132083

Add tests for RT#132083 | [REGRESSION] Broken math (-2147483648 != -2147483648)

---

S32-num/rat.t

#125215: [BUG] 10 ** -1 is a Num, but should probably be a Rat since it can in Rakudo
https://rt.perl.org/Ticket/Display.html?id=125215

Add tests for RT#125215 | [BUG] 10 ** -1 is a Num, but should probably be a Rat since it can in Rakudo

---

S02-lexical-conventions/comments.t
S10-packages/precompilation.t
S11-modules/InnerModule.pm
S11-modules/OuterModule.pm
S17-supply/batch.t
S22-package-format/local.t
S24-testing/test-data/line-number-cmp-ok.txt
S24-testing/test-data/line-number-dies-ok.txt
S24-testing/test-data/line-number-eval-dies-ok.txt
S24-testing/test-data/line-number-eval-lives-ok.txt
S24-testing/test-data/line-number-is-deeply.txt
S24-testing/test-data/line-number-is.txt
S24-testing/test-data/line-number-is_approx.txt
S24-testing/test-data/line-number-isa-ok.txt
S24-testing/test-data/line-number-isnt.txt
S24-testing/test-data/line-number-lives-ok.txt
S24-testing/test-data/line-number-nok.txt
S24-testing/test-data/line-number-ok.txt
S24-testing/test-data/line-number-throws-like.txt
S24-testing/test-data/todo-passed.txt
S32-basics/warn.t
S32-exceptions/misc.t
S32-io/IO-Socket-INET.pl
S32-trig/TrigTestSupport
integration/advent2012-day06.t
integration/error-reporting.t

The commit looks safe to me to merge, but since this is 6.c-errata branch, I figured it could use a pair of extra eyes to look over it first.

Use `v6.c` instead of `v6` so we get right language version when 6.d comes out

---

S03-junctions/misc.t

#131490: Crash in Junction:D.BUILDALL `This type (Scalar) does not support elems`
https://rt.perl.org/Ticket/Display.html?id=131490

Add test for RT#131490 | Crash in Junction:D.BUILDALL `This type (Scalar) does not support elems`

---

S26-documentation/07-tables.t

Reverts perl6/roast#363
GH#1291 is not merged yet, so it's a bit too early for this to be merged.

Revert "add tests for fix for RT #126740"

---

S02-names/strict.t

RT#125183: https://rt.perl.org/Ticket/Display.html?id=125183
I think the test description could use improvement but don't know how to describe the operation better than "postcircumfix {}".

`no strict` autovivification 2 level hash

---

S26-documentation/08-formattingcodes.t

This adjusts for rakudo/rakudo#1300.
- rejigs the array indexes so that the tests work without "" being
everywhere
- adds a new test B< < B<foo> > > which used to fail

Formatting Codes don't produce spurious ""

---

S02-literals/allomorphic.t
S02-literals/quoting-unicode.t
S02-literals/quoting.t

This tests for bugs exhibited in
[Issue 1204](https://github.com/rakudo/rakudo/issues/1204).
Corresponds with development in Rakudo:
[Commit ad684de383bb0c0ff051d7b0901583a9b5c2e398](https://github.com/rakudo/rakudo/commit/ad684de383bb0c0ff051d7b0901583a9b5c2e398)
[PR 1350](https://github.com/rakudo/rakudo/pull/1350)
This does not provide cover every variation of the quoting syntax, but
hopefully provides sufficient coverage.

Test Issue 1204 (Strip slip in quotewords)

---

S32-temporal/Date.t

Hi,
I fixed RT#127016: https://rt.perl.org/Public/Bug/Display.html?id=127016
The changes are:
+ Make sure Date.new(Int, 1, 1) dies [e1aeb1d]
rakudo: https://github.com/rakudo/rakudo/pull/1363

Fix RT#127016

---

S32-list/rotor.t

Test courtesy of zoffix.
Addresses
[Rakudo Issue 1397](https://github.com/rakudo/rakudo/issues/1397)

Rakudo Issue 1397: Test Rotor iter stops pulling after IterationEnd

---

S02-types/bag.t

For issue #1438, which was just fixed today.

Add a test for picking a Bag with an argument smaller than the Bag size.

---

S03-operators/relational.t

See <https://github.com/rakudo/rakudo/issues/1304>.
Depends on <https://github.com/perl6/nqp/pull/402> and <https://github.com/rakudo/rakudo/pull/1448>

Rakudo Issue 1304: Unfudge now passing negated chain tests on JVM

---

S04-declarations/state.t

Test that statevar values in blocks following "do" statement prefix is
not reset on each iteration.
See [Rakudo Issue 1341](https://github.com/rakudo/rakudo/issues/1341)

Rakudo Issue 1341: Statevar not reset after do statement prefix

---

packages/Test/Util.pm

See issue #395.  Since we change Test::Util run-with-tty we also effect S32-io/out-buffering.t as well as S16-io/eof.t.  On WSL/ubuntu 16 out-buffering.t also breaks the terminal but it ran OK on WSL ubuntu 14 since, unlike eof.t, the script process did not read from stdin.  Having the out-buffering.t test run on ubuntu 14 does not seem FTM worth a more complicated patch.

S16 io eof wsl script fudge

---

S12-attributes/mutators.t

There seems to be more than one school of thought about using attribute mutators.  There is the @jnthn school of thought discouraging their use as mentioned in the header comment referring to the [6guts blog post](https://6guts.wordpress.com/2016/11/25/perl-6-is-biased-towards-mutators-being-really-simple-thats-a-good-thing/) and the @zoffixznet school of thought which seems more tolerant based on his [recent advent post](https://perl6advent.wordpress.com/2017/12/02/perl-6-sigils-variables-and-containers/) (the end of the section of the post on "Customizing").  I don't know which school of thought wins but believe we can do better than leaving the test broken.

Fix attribute mutator tests and add comment discouraging use

---

S12-methods/class-and-instance.t

Tests for class and instance only methods selected by invocant concreteness (eg ::?CLASS:[U|D]:).
GH roast issue #217.

Update class-and-instance.t - tests for class and instance only methods

---

S05-mass/stdrules.t

Doesn't throw 'Iteration past end of iterator'.
Is it sufficient to just test behavior or should it also have something like
lives-ok? I figure that if it panics and is uncaught it will alert us to failure
all the same?

Rakudo Issue 1622: Test empty negative char class doesn't fail

---

S02-types/array.t
S02-types/hash.t
S06-signature/unspecified.t
S32-list/sort.t
packages/Test/Util.pm

Covers https://github.com/rakudo/rakudo/issues/1739
And tweaks existing tests to handle compile-time/non-multi dispatch failure detection.

Proto fix r1739

---

S11-repository/curli-install.t

The intent of this test is installing a Distribution, and the fact
it used a class called Distribution to do it should be irrelevant.
This instead installs something that *does* Distribution.
Changed s/$path/$repo-path/ for clarity since $path is used as a
variable name elsewhere.

Test installation with proper Distribution usage

---

S02-literals/array-interpolation.t

If an implementation tried to interpolate @array into "@array", the test would still pass.

Change test so that it will actually fail

---

S06-other/misc.t

It's not mentioned anywhere, except in comments, far as I have seen.

dd → say since dd is rakudo specific

---

S32-num/rounders.t

Add tests for rakudo/rakudo#1745 plus some more for 2-argument version of &round.

Tests for rakudo/rakudo#1745.

---

S32-str/encode.t

And some reasonable additional tests.

Adds test for translate-nl

---

S09-typed-arrays/native.t

splicing as well.
Corresponds to the following
[Rakudo development](https://github.com/rakudo/rakudo/pull/2240)
I'm not sure this the most appropriate place for the splicing tests as the
other splice-related tests are in the type-specific native array files. But I
also wanted to minimize duplication as the code can be shared between
STORE and splice tests.
If the splice tests are better elsewhere let me know and I'll move them.

Test STOREing / splicing lazy Seq into native array throws

---

S02-literals/numeric.t

This commit goes with issue [Rakudo/#2094](https://github.com/rakudo/rakudo/issues/2094) on GitHub. In the current release of Rakudo `42.:<->` errors from an overaggressive check to prevent integers from ending with fullstops. This commit checks to confirm that `42.:<->` does equal `-42`. 
The corresponding pull request for Rakudo is [#2225](https://github.com/rakudo/rakudo/pull/2225).

Check .:< ... > for prefix operators on int literals

---

MISC/bug-coverage.t

Covers bugs fixed by
https://github.com/rakudo/rakudo/commit/64ddacab8f
https://github.com/rakudo/rakudo/commit/9738dfbf21
https://github.com/rakudo/rakudo/commit/d1e80dfe28
https://github.com/rakudo/rakudo/commit/9ff1736761
Merge was blocked by R#2075 https://github.com/rakudo/rakudo/issues/2075
as some of the opt methods return incorrect values after IterationEnd

Cover more iterator opt tests

---

S02-types/multi_dimensional_array.t

This pull request enables a previously disabled shaped array test set
and changes one of its tests to the behaviour discussed [here](https://github.com/rakudo/rakudo/issues/2351).
It also adds a subtest that generates tests for arrays up to n dimensions to catch bugs like these:
https://github.com/rakudo/rakudo/pull/2350
https://github.com/rakudo/rakudo/issues/2352
because they are less commonly used.
It is currently set to three because of the latter.

Shaped array test improvements

---

S12-enums/thorough.t
S32-exceptions/misc.t
S32-io/chdir.t

This fixes a cases where the spectest is accidentally outputting invalid TAP.

Fix various TAP errors

---

S17-supply/watch-path.t

This PR addresses a few issues with the watch-path tests on macOS.  Unfortunately it makes the test take a little over 2 minutes to run [and it does still occasionally generate incorrect failures] but this is the only combo that regularly passes on my machine.
In the long term it would be better to find a way of waiting up to a specified timeout for each expected event, rather than just counting hits and having to find a timeout that's "mostly ok" without spending too much time waiting.
I'm uncertain about the specified behaviour in https://github.com/perl6/roast/commit/dcf672cfb2d3cb4fd81f3c028784fd24f82bb2b4.  It seems that we don't get an notification for opening an existing file for append.  That seems sensible to me, but the wording on the test doesn't make it clear whether or not …

Fix macos watch-path

---

S32-str/utf8-c8.t

This test was causing errors on macOS with the following message:
/bin/sh: Lon: Illegal byte sequence
/bin/sh on macOS 10.14.1 is Bash 3.2.57.  This patch takes the shell
out of the equation by using `run` instead of `shell`.

Fix issue with macOS /bin/sh and weird source names

---

S11-modules/require.t
packages/S11-modules/lib/InnerClass.pm6

I have a PR coming to `rakudo` branch that merges `require stub:file<>` class symbols into `stub`, right now they're just ignored.
This test is fixed by see:rakudo/rakudo#2789

add tests for require:file<> containing classes

---

S09-subscript/slice.t

The test shows how various subscripts should relate. The one that was failing as a result of rakudo/rakudo#2872 is
``` perl6
is-deeply (^3)[0 ..^ *],         (0, 1, 2), 'Whatever range exclusive';
```

Add test for rakudo/rakudo#2872

---

S06-signature/type-capture.t

Checks if `Scalar` container `$!default` is set to instantiated type capture.

Test for rakudo/rakudo#2169

---

S17-channel/basic.t

Added tests asserting that the `status` of a closed promise previously acquired from a `Channel` is updated by `close` and `fail`.

Added regression tests for github #2985.

---

S17-channel/basic.t

All tests now check a previously acquired closed promise to ensure it's not
the measurement that kills the cat.
This should cover all changes proposed in rakudo/pull/2987 and a bit more.

Rigorous testing of Channel close/fail logic

---

S11-modules/require.t
packages/S11-modules/lib/GH2983.pm6

Testing if type objects and constants are imported as is while scalars
preserve their container.
rakudo/rakudo#2983

Tests for rakudo/rakudo#3005

---

S02-names/pseudo-6c.t
S02-names/pseudo-6d.t
spectest.data

Tested scenarios are: compile time with combinations of EVAL and BEGIN.
rakudo/rakudo#3058

Add tests for CORE:: symbols availability

---

S11-modules/importing.t
S11-modules/versioning.t
packages/S11-modules/lib/Module_6c.pm6
packages/S11-modules/lib/Module_6d.pm6
packages/S11-modules/lib/Module_6e.pm6
packages/S11-modules/lib/NoPrecompilation.pm6

Test a few more scenarios of combinations of `use`/`require` with module and run-time code versions. Special focus on `EVAL`ed code.
Followup to rakudo/rakudo#3116 and rakudo/rakudo#3113

Tests for Rakudo issue 3116

---

S02-names/pseudo-6e.t
packages/S02-names/lib/Pseudo6c.pm6
packages/S02-names/lib/Pseudo6d.pm6
packages/S02-names/lib/Pseudo6e.pm6

Test for namespaces referring their respective COREs and for valid
multi-dispatching over symbols from different COREs.
- perl6/problem-solving#80
- rakudo/rakudo#3112

Add tests for CORE::v6<rev> pseudo-packages

---

packages/Test-Helpers/lib/Test/Util.pm6

Reverts perl6/roast#572
As @ugexe suggested, some tests might imply full control over their libpath.

Revert "Include path for subprocess"

---

S05-grammar/namespace-6e.t
spectest.data

It must be possible to create grammars named `Grammar`
rakudo/rakudo#3132

Test for 6.e grammar Grammar name

---

S12-meta/classhow.t

Closes https://github.com/rakudo/rakudo/issues/2607
The question at https://github.com/rakudo/rakudo/issues/2607#issuecomment-455559432 asks if the test should live in roast or rakudo suite.
My guess is that roast is the correct place, because we likely want all proper Raku compilers to be able to do what's in the test, because MOP totally allows that, so this is not a rakudo-specific issue.

Test runtime-created classes being attributes

---

S17-procasync/many-processes-no-close-stdin.t
S17-procasync/no-runaway-file-limit.t
S17-procasync/stress.t

There are 1200 iterations of a loop to try to reproduce the memory corruption bug.
Without the fix, typically fails after 500-800 iterations.
With the fix, takes about 13 seconds on my machine for all 1200 iterations.

Add a test for rakudo/rakudo#3299 Proc::Async memory corruption bug.

---

S26-documentation/why-trailing.t

In the current rakudo version 2019.11 this is broken. On the current
rakudo/rakudo master branch this passes. I extended the test, so we
shall never more break this functionality.

Extend test for trailing documentation on sub params

---

S03-smartmatch/any-type.t

Also structurize tests using `subtest` routine.
In support of rakudo/rakudo#3385 and rakudo/rakudo#3383

Add tests for smarmatching of parameterized Array against Positional

---

S11-modules/import-long.t
packages/S11-modules/lib/LongNames.rakumod
spectest.data

Test for symbols declared with long names are exported and imported correctly.
Covers perl6/problem-solving#142

Test for export of long names

---

S17-channel/basic.t

This tests rakudo issue [2646](https://github.com/rakudo/rakudo/issues/2646).

channel elements not yet consumed in the supply should still be accessible

---

S06-advanced/dispatching.t
spectest.data

Method, multi, and wrapper dispatchers must not break each other and return control to the previous dispatcher when exhausted.
In support of rakudo/rakudo#3500

Additional tests for dispatching

---

S26-documentation/block-leading-user-format.t

By putting it in here. Closes #640.

Fix external dependency

---

S32-str/sprintf.t

The issue was an LTA error for interpolated '$' symbols in sprintf
format strings.
This commit:
+ removes a duplicate test which is already in Rakudo "t/05-messages/02-errors.t"
+ adds a messsage check to the remaining tests
File affected:
+ S32-str/sprintf.t

Add test for Rakudo issue GH #3682

---

S17-procasync/print-raw-arguments.p6
S17-procasync/windows-arg-quoting.t

This PR adds tests for [Raku/problem-solving#20](https://github.com/Raku/problem-solving/issues/20).

Add tests for Windows specific Proc argument quoting

---

CONTRIBUTING.md
README.md
spectest.data

- Extend CONTRIBUTING.md with information about problem-solving repo,
correct references, and added more sanity to test examples. Got rid of
more `perl6` notions.
- Cleaned up spectest.data header from all Rakudo-specific information.
Replaced RT references with GitHub.
Fixes #654

Improve documentation

---

S04-phasers/interpolate.t
S04-statements/lazy.t
S04-statements/leave.t
S05-modifier/exhaustive.t
S05-modifier/ratchet.t
S06-advanced/dispatching.t
S06-macros/postfix.t
S06-macros/returning-closure.t
S06-macros/returning-string.t
S10-packages/export.t
S10-packages/scope.t
S12-attributes/augment-and-initialization.t
S13-syntax/aliasing.t
S14-roles/attributes-6e.t
S14-roles/composition.t
S14-traits/package.t
S14-traits/variables.t
S16-unfiled/getpeername.t
S17-supply/watch-path.t
S24-testing/2-force_todo.t
S26-documentation/12-non-breaking-space.t
S32-io/child-secure.t
S32-list/toggle.t
S32-str/space-chars.t
fudge
packages/S11-modules/lib/GH2979.pm6
packages/S11-modules/lib/OuterModule.pm6
spectest.data

In elaboration of #657 
Aside from evaluating and fixing the tests, this PR introduces a slight change to `fudge` by extending the `eval` verb functionality to suppress `EVAL`-thrown exceptions and produce as many `flunk` as necessary if `EVAL` fails. All this done under `todo` to make harness report _TODO passed_ if the evaled tests are passing.

Putting a few things in order

---

rosettacode/greatest_element_of_a_list.t
rosettacode/sierpinski_triangle.t

The comments of the two rosettacode tests updated to refer to the (updated on their end) “#Raku” url anchor.

Rosettacode comment updates

---

S04-phasers/in-loop.t

Closes R#1900 rakudo/rakudo#1900
For comparison:
```
$ perl6 --version
This is Rakudo version 2018.05 built on MoarVM version 2018.05
implementing Perl 6.c.
$ perl6 -Ipackages/Test-Helpers/lib S04-phasers/in-loop.t 2>&1 | grep LOOP
Useless use of LOOP_BLOCK_3 symbol in sink context (line 237)
```
```
$ raku --version
This is Rakudo version 2020.07 built on MoarVM version 2020.07
implementing Raku 6.d.
$ raku -Ipackages/Test-Helpers/lib S04-phasers/in-loop.t 2>&1 | grep LOOP | wc -l
0
```
Note that, annoyingly, the test _also_ passes in 2018.05 because in that version for some reason Test::Util's  `doesn't-warn` doesn't seem to work as expected.

Test FIRST statement in loop does not warn

---

S02-types/baghash.t

This is a first round of tests for .pick/pickpairs/grab/grabpairs with a Callable argument, for BagHash. Similar tests could be added if desirable for Bag, Mix and MixHash.
Note that the test for .pickpairs fails with current rakudo as I think its implementation may be wrong: PR to come about it.

Test BagHash.pick/pickpairs/grab/grabpairs(Callable)

---

S06-other/main.t

To be merged after https://github.com/rakudo/rakudo/pull/3947 has
been merged.

Add tests for fix of R#3929

---

S32-num/cool-num.t

I think I noticed it was uncovered in a coverage report, writing these
found a (now fixed) bug in Bool.Numeric, so that was good.

Add a bunch of tests for truncate(Cool)

---

S32-io/copy.t

The issue: Attempting to copy a directory to a file fails as expected, but the file is deleted.
The fix: In IO::Path method copy add an initial check for the self and $to IO types and fail immediately if self is a directory and $to is a file. 
This commit:
+ Adds a new subtest to ensure (1) such an attempt is detected and results in a failure, (2) the failure message is as expected, and (3) the target $to file is unaffected.
File affected:
S32-io/copy.t

Add test for issue #3971

---

S14-roles/mixin-6c.t
S14-roles/mixin-6e.t
spectest.data

Primarly to make sure that cases like `0 but True` are not broken. So,
`mixin-6e.t` is basically a copy of `mixin-6c.t` with few cases removed
where 6.e-declared roles are mixed into core classes. These tests would
require the roles to be declared externally, in a 6.c versioned module
which would eventually wind down to the same testing we already do in
mixin-6c.t.
- Added a test for in-role declared constructor to be invoked upon mixin
under 6.e
In support of rakudo/rakudo#3997

Add testing of mixins under v6.e

---

S24-testing/1-basic.t

Primarilty to take care of `isa-ok Any.HOW, Metamodel::ClassHOW` case.

Add tests for isa-ok matching against metaclasses

---

S14-roles/versioning.t

Follow up to rakudo/rakudo#4046. Make the test check for
`X::Language::IncompatibleRevisions` exception instead of AdHoc.
And don't expect cross-language mixins to die because they don't now.

Test for the right exception and don't disable mixins

---

S32-io/IO-Socket-INET.t

My first attempt at https://github.com/rakudo/rakudo/pull/4047 typed
families as `ProtocolFamily(Int:D)`. This passed Roast despite making the
method accept invalid `Int:D` values.

Add a test for invalid Int:D families for IO::Socket::INET.new

---

S02-types/nominalizables.t
spectest.data

Test for subsetting a coercion and nested coercers.
In support of rakudo/rakudo#4058

Add tests for nominalizables

---

S32-basics/warn.t

The smartmatch should return `False`. But the problem it supposed to
test for, as stated in rakudo/rakudo#1833, is to make sure no warning is
produced by the match. This job is still done well by the test.
In support of rakudo/rakudo#4076

Change the meaning of List ~~ List.new test

---

S02-literals/allomorphic.t
S13-overloading/typecasting-long.t
integration/weird-errors.t

In support of rakudo/rakudo#4096. Previously the invocation handler was unconditionally using a coercion method named after the target type. Now it uses the new coercion protocol. With this change `Str($*USER)` ends up as `IntStr` because no actual coercion is needed. Correspondingly, testing for the outcome of it to be a `Str` class makes more sense than to test for it to be exactly a `Str` instance.

Make test conform to the new coercion semantics and role invocation

---

fudgeall

The latter is only available in Perl v5.16 (and later), and is a compile
time failure on earlier Perls. However, we don't *need* the tag - its
purpose is to *override* CORE::glob with `bsd_glob`. As we make a direct
call to `bsd_glob` we only need to import *that*, which works all the way
back to v5.6.0 or so.
With this change fudgeall works with system Perl on Solaris 5.11, which is
v5.12.5.

Import `bsd_glob` from File::Glob, not the tag `:bsd_glob`.

---

S09-subscript/slice.t

It turns out that nested array slices were broken, i.e. using them
returned the wrong results.
This was reported in https://github.com/Raku/old-issue-tracker/issues/6233
During lizmat++ work to improve array slices it also turned out
that there were no tests in roast for the above reported issue.
This PR rectifies this omission.

Add tests for nested array slices

---

S32-list/create.t

Seems that the List creation via 'is List' wasn't tested.
As this is basic syntax I think tests are deserved in roast.
Can be merged after merging  https://github.com/rakudo/rakudo/pull/4208

Tests for rakudo PR #4208

---

S32-encoding/registry.t

Rakudo.moar was previously passing a test for utf32 support despite not actually supporting utf32.  This updates the test to more
reliably test for utf32 support and marks the test as todo for the MoarVM backend.
Without this change, rakudo/rakudo#4232 fails Roast spectests.
Related issues:  rakudo/rakudo#3293 and MoarVM/MoarVM#1348

Mark utf32 tests as todo for rakudo.moar

---

S32-str/utf8-c8.t

The test needs to skip on Apple's file systems.
The value of $*KERNEL is consistent across releases, whereas what
$*DISTRO.name reports has changed from "macosx" to "macos" with Apple's
rebranding.

Use $*KERNEL instead of $*DISTRO.name to skip tests on "OS X"/"macOS".

---

S06-signature/introspection.t

Make sure that `:([])` and `:(@)` are different signatures, whereas
two `:([])` or even two `:([$a, *@])` are the same thing.
Followup to rakudo/rakudo#4258

Test for eqv op on destructured signatures

---

S24-testing/3-output.t

Take into account additional header from a subtest output which reports
subtest message and looks like:
Also improve testing for indented lines. If we ever decide to change the
number of spaces in subtest indentation then we won't need to change the
test. It now allows any number of spaces but only ensures the number
doesn't change across subtest output.
Support for rakudo/rakudo#4280 and rakudo/rakudo#4266

Improve test for subtest output

---

S32-temporal/DateTime-Instant-Duration.t
S32-temporal/DateTime.t

Rakudo issue #4286 is a suggestion to modify class DateTime's method 'posix' to return a Real value instead of an Int as is done at present. During an initial attempt to do so, 17 tests failed and indicate deeper changes need to be made beyond the obvious one. 
This PR is to ensure that any future attempts to change the return type to Real will have a list of known problems to investigate.
This PR has been checked with a full spectest on the current Rakudo master branch to ensure there are no issues with this "no-op" change.

Identify tests to fix when changing DateTime.posix to return a Real value

---

S17-lowlevel/lock.t

There's another test for non-predicate `wait`, so we're good here. Refs (and maybe solves) rakudo/rakudo#4275

Changes to test new predicate `wait`

---

S32-temporal/greg-jd-frac-seconds.t
spectest.data

Test round-tripping Julian date to/from DateTime instants with fractional seconds (to hundredths of a second).
Test data have been validated with the NASA JPL Time Conversion Tool.

Add tests for fractional seconds

---

S07-hyperrace/basics.t

`HyperSeq` and `RaceSeq` should throw if an iterator has been already
produced for them, similar to what `Seq` currently does.
In support of rakudo/rakudo#4416 and rakudo/rakudo#4413

Add tests for hyper/race throwing on second .iterator

---

S26-documentation/02-paragraph.t

Lowercase strings in E<> should be valid HTML5 entities. The corrected test will fail without the corresponding Rakudo PR, so please merge rakudo/rakudo#4427 at the same time as this one. The fix could not be easily implemented for JVM due to Raku/nqp#727, so this also fudges the test under JVM

Align test #28 of S26-documentation/02-paragraph.t with intended design of E<>

---

S26-documentation/08-formattingcodes.t

This adds tests for character entities/escapes in Pod as designed in https://design.raku.org/S26.html#Entities. Some of them won't pass without rakudo/rakudo#4428, so please don't merge this until that PR is merged first.

Add tests for Pod E<>

---

S14-roles/generic-subtyping.t
spectest.data

The bug WRT the `roles` metamethod does not appear to be possible to trigger without invoking it directly because the `$transitive` flag is set to `0` in noteworthy exposed metamethods that depend on it.
See https://github.com/rakudo/rakudo/pull/4436

Add tests for type constraints on forwarded, constrained generics

---

S02-lexical-conventions/comments.t
S32-exceptions/misc2.t

The TODO is now passing, and the new exception thrown is a better one.
Should only be merged if/when https://github.com/Raku/nqp/pull/732 is merged and Rakudo is bumped.

Track changes caused by NQP PR #732

---

S02-types/list.t

The previous version of the test expected the same container to be preserved for an itemized list despite roundtripping it through `EVAL`. But this is incorrect because:
- we itemize two different lists despite both being empty
- why would method `item` always return same scalar container, whatever
it wouldd mean in terms of comparing two containers
- and then we expect `EVAL` method to somehow preserve that container
despite the string recevied from `raku` method does not provide us
with any hints about the container details
So, the only correct approach for this test is to make sure that both lists: directly itemized and roundtripped one, - are contained by the same type of container.
In support of Raku/problem-solving#291

Use more correct approach in list EVAL roundtrip

---

S02-types/native.t

Make sure thay match against `Real`, `Numeric`, and `Stringy` roles.

Add typecheck tests for natives

---

S03-smartmatch/signature-signature.t
S06-signature/closure-parameters.t

Cover issue rakudo/rakudo#4537 and support PR rakudo/rakudo#4538:
- Unfudged now passing tests
- Added some negative tests to make sure we're not positive only
- Added tests to make sure named constrained parameters work too
- Added tests for generics

New tests for signature-constrained parameters

---

integration/weird-errors.t

Depending on how many more than 8192 there were you'd get weird throws
or segfaults, but this checks that the code compiles and runs fine.

Add test for no segv with more than 8192 variables

---

S32-num/expmod.t

This way when it starts passing we'll know to un-todo it.

Turn a skip in expmod tests into a todo

---

S03-smartmatch/signature-signature.t

Covers the bugs noted in https://github.com/rakudo/rakudo/issues/4558. Requires https://github.com/rakudo/rakudo/pull/4573.

Add more tests for type constraints in signature smartmatches

---

S14-roles/versioning.t
packages/S14-roles/lib/Ver6c.rakumod
packages/S14-roles/lib/Ver6e.rakumod

Applying 6.e role to a pre-6.e class is no more an error. Make sure it
works as expected.
In support of rakudo/rakudo#4686

Change testing for cross-language revision class/role

---

S16-filehandles/filetest.t

The methods are just not implemented. It doesn't make sense to have
a special case for Windows. Also IMHO it's cleaner to just skip the
whole block instead of maintaining different skip directives.
Please note that the tests for "README".IO didn't work as well.
They have been unfudged back in 2014 with commit ba936a5c8c, but
as far as I can see that was only possible because Rakudo's "README"
has been renamed to "README.md" a while ago
(https://github.com/rakudo/rakudo/commit/633d1fa591).

Simplify fudging for :M, :C, :A

---

S02-types/built-in.t
S03-sequence/arity-2-or-more.t

The tests are still very specific wrt the error message, but they now
allow to mention the method, for instance:
$ ./rakudo -e 'my $foo = ObjAt.new(:val("test")); $foo ~~ /"foo"/;'
Too few positionals passed to 'new'; expected 2 arguments but got 1
in block <unit> at -e line 1
The old messages that talked about parameters have been removed back in
2015 with https://github.com/MoarVM/MoarVM/commit/288410e40d and
https://github.com/rakudo/rakudo/commit/3301ec44b7.

Tweak tests for error message for wrong arity

---

S26-documentation/block-leading.t
S26-documentation/block-trailing.t
S26-documentation/wacky.t
S26-documentation/why-both.t
S26-documentation/why-leading.t
S26-documentation/why-trailing.t

This required to remove tests which were testing for `Role.WHY` returning `Nil`. But as was suggested in this comment:
https://github.com/rakudo/rakudo/pull/3549#issuecomment-687587580
the tests were needed to ensure that a documentation comment is attached to a particular parametric role, not to its group. But since rakudo/rakudo#3549 makes `.WHY` delegate to the default candidate, these tests doesn't make sense anymore. Instead why-both.t now makes sure what we get from a role group is the same object we get from the default candidate.
Alongside with the essential changes, also unified all tests with regard to use of idential test assertion subs. They all now are `subtest` based.

Make sure role group delegates .WHY to its default candidate

---

S03-smartmatch/00-sanity.t

Negated smartmatch must always boolify

Add negation tests

---

S03-smartmatch/00-sanity.t
S12-meta/primitives.t

- Fixed errors in a test of `Metamodel::Primitives` revealed by further smartmatch improvements
- Randomized order of tests in smartmatch sanity testing in order to increase chances of catching some order-dependent class of regressions.

Adjust tests to better work with improved smartmatch dispatcher on MoarVM

---

S12-attributes/instance.t

Two S12-attribute regression tests checked the exact value of an error's `$.declaring` property (expecting it to be `n attribute`).  This
changes the matcher to test that `$.declaring` contains `attribute`, which seems more robust.
This supports rakudo/rakudo#4786 (which changes `$.declaring` from `'n attribute'` to `'an attribute'`) but, because the test is overspecific, I believe this PR to be justified regardless of whether that one is merged.

Fix over-specific regression test

---

S32-list/categorize.t
S32-list/classify.t

The previous version of these tests was a statement of buggy behavior where classify was autothreading over junctions internally and producing incorrect results. This version establishes less confusing and more useful standard of method's behavior.
Note that in order to pass `classify.t` currently requires PR rakudo/rakudo#4769 as only when junctions are value objects the classification would correctly put all values into the same basket. Otherwise we're going to end up with indivudual key for each single junction object even if two or more of them are identical.
- resolves raku/problem-solving#312
- requires rakudo/rakudo#4770 and rakudo/rakudo#4769

Accommodate tests to fixes of classification over junctions

---

S09-hashes/objecthash.t

A companion PR for rakudo/rakudo#4788, which makes the todo'ed test of using Mu as a Hash key now passes.

Un-todo passing test

---

S32-io/io-path-cygwin.t
S32-io/io-path-unix.t
S32-io/io-path-win.t

Specifically test absolute paths containing updirs and paths only made up
of updirs but still having a basename.
Needs rakudo/rakudo#4795 merged to pass.

Add more IO::Path::parent tests

---

S14-roles/parameterized-basic.t

It was an old bug causing a cascaded exception thrown when an error about unimplemented multi-candidate was reported if the prototype used ::?CLASS in its signature.
The new test requires rakudo/rakudo#4912.
Fully resolves rakudo/rakudo#3483

Add a test for error thrown for ::?CLASS used in a role

---

S06-signature/passing-arrays.t

It must not work for a `List`-typed argument, as was attempted in rakudo/rakudo#4864. Therefore the test for binding a `Seq` to a `List` parameter makes no sense. Consider rakudo/rakudo#4951 instead.
Removing TODO too.

Fix a mistake about positional bind failover

---

S17-supply/snip.t
S32-list/snip.t

To go with https://github.com/rakudo/rakudo/pull/4976

Add tests for snip functionality

---

S09-multidim/indexing.t

add minimal test for partially dimensioned views of fixed-sized array, which are NYI at the moment I think.
In relation with https://github.com/Raku/old-issue-tracker/issues/6075

add lives-ok test of partially dimensioned view

---

S06-signature/defaults.t

See https://github.com/rakudo/rakudo/pull/4648. Just check for the named variants, since the differences between them and optional positionals aren't relevant to `Binder`'s `&handle_optional`.

Typecheck optional @/% parameters' defaults

---

S02-types/nested_arrays.t

Since `@b[3]` itself returns a Failure it is not necessarily immediately throws. Ensure that it does.

Make the tested code always throw

---

S14-roles/versioning.t

This doesn't affect older compilers but makes the spectesting happy with rakudo/rakudo#5157

Stringify language revision

---

S14-roles/typecheck.t

Make sure a role matches a parent of its parent class, or a role consumed by any parent.
In support of rakudo/rakudo#5266

Add a test for typechking of roles against parent classes

---

test_summary

This reflects some recent changes of the directory structure for tests:
* Tests for Rosettacode have been removed in 2023-02, see https://github.com/Raku/roast/commit/504f0265ee
* Specific tests for 6.c and 6.d have been moved to dedicated dirs in https://github.com/Raku/roast/commit/720a5dc1f8 and follow-up commits
The change to the list of dirs doesn't really change the functionality of the script. It only avoids some warnings/errors regarding unknown or non-existing dirs. (One could argue that either the variable name or the logic of grouping tests per Synopsis should be updated, because the directory structure doesn't match the Synopsis names anymore. But maybe it's not worth the trouble.)

Update list of dirs for test statistics

---

S02-types/array-shapes.t

It looks like these tests have been added on the wrong assumption that adding a dot between the array name and the shape declaration should fail. At the time when the tests were added the synopsis (S09-data.pod) stated that those forms are errors. Later on it was clarified that they aren't supposed to die, but just can't be used to declare shaped arrays: https://github.com/Raku/old-design-docs/commit/e8527c2291.

Fix tests for arrays that aren't shaped

---

S02-names/is_default.t

- Test all variants of hash parameterization of key and value.
- Fix tests for `is default` type check failures on attributes.

Improvements to `is default` tests for hashes

---

S17-supply/construction-recursion.t

Having a supply that recurses back to itself during construction and forcing a (temporary) blocking of that supply has proven to be a corner case that's difficult to get right. Thus add a test for it.
https://github.com/rakudo/rakudo/issues/5141 tells the full story of how this test came to be.
Depends on https://github.com/rakudo/rakudo/pull/5202.

Test supply setup with a blocking recursion

---

S32-num/cool-num.t
S32-num/log.t

Routine 'log2' was incorporated into core earlier, but tests were not added then. This PR adds basic coverage for 'log2'.

Add tests for log2
